# Dockerfile.api
FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps --omit=dev

# Copy source code
COPY . .

# Expose API port
EXPOSE 5000

# Start the API
CMD ["npm", "start"]
